# Here, "a.out" is the target, and "hello.c" is a dependency. If a.out does
#  not exist, or if it is older than hello.c, then the command "gcc ..." will
#  be run in order to (re)build a.out.
a.out: hello.c
	gcc -Wall -Wextra -Werror -ansi -pedantic hello.c
